name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install libsystemd-dev podman bats
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.0'

    - name: Vendor
      run: go mod vendor

    - name: Test
      run: go test -mod=vendor -v ./...

    - name: Run BATS unit tests
      run: bats test/unit-test.bats

    - name: Run BATS integration tests
      run: bats test/intergrated-tests.bats

    - name: Run BATS keycloak tests
      run: bats test/keycloak-tests.bats
